default: &default
  adapter: postgresql
  pool: <%= ENV['RAILS_MAX_THREADS'] || 5 %>
  timeout: 5000
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  schema_search_path: public

development:
  <<: *default
  database: mtg_decks_development

test:
  <<: *default
  database: mtg_decks_test
  host: localhost

production:
  <<: *default
  database: mtg_decks_production